### ISSUE TITLE
Change point detection method for uStar Threshold estimation produces NAs for example dataset

### ISSUE THREAD

**Issue by lsigut** [bgctw/REddyProc#14] opened 2018-08-14 21:59 UTC
Hello,
I tried several things but I still get NA uStar thresholds when using CPT. I am running the newest R version 3.5.1 (2018-07-02), the newest RStudio Version 1.1.456 and CRAN REddyProc 1.1.5. I tried to update the tidyverse packages as suggested on GitHub. I was not able to install REddyProc from GitHub through devtools::install_github("bgctw/REddyProc"). This seems to be unrelated issue that devtools currently do not recognize Rtools produced by Rtools35.exe. Here is a reproducible example with some console outputs:

`library(REddyProc)`
`fileName <- getExamplePath('Example_DETha98.txt', isTryDownload = TRUE)`
`EddyData.F <- if (length(fileName)) fLoadTXTIntoDataframe(fileName) else  Example_DETha98`
`EddyDataWithPosix.F <- fConvertTimeToPosix(EddyData.F, 'YDH',Year.s = 'Year',Day.s = 'DoY',Hour.s = 'Hour')`
`EddyProc.C <- sEddyProc$new('DE-Tha', EddyDataWithPosix.F, c('NEE','Rg','Tair','VPD', 'Ustar'))`
`EddyProc.C$sEstUstarThreshold(ctrlUstarEst.l = usControlUstarEst(isUsingCPTSeveralT = TRUE))$uStarTh`

With output:
  aggregationMode seasonYear  season uStar
1          single         NA    <NA>    NA
2            year       1998    <NA>    NA
3          season       1998 1998001    NA
4          season       1998 1998003    NA
5          season       1998 1998006    NA
6          season       1998 1998009    NA
7          season       1998 1998012    NA

and alternative:

`season_factor <- usCreateSeasonFactorMonthWithinYear(
  EddyDataWithPosix.F$DateTime - 15 * 60)`
`table(season_factor)`

`EddyProc.C$sEstUstarThreshold(ctrlUstarEst.l = usControlUstarEst(
  isUsingCPTSeveralT = TRUE), seasonFactor.v = season_factor)$uStarTh`

with similar results:
  aggregationMode seasonYear  season uStar
1          single         NA    <NA>    NA
2            year       1998    <NA>    NA
3          season       1998 1998003    NA
4          season       1998 1998006    NA
5          season       1998 1998009    NA
6          season       1998 1998012    NA

Is there maybe some dependence used only for CPT that I should try to update?
Thank you!

**Comment by bgctw** [comment] 2018-08-15 06:51
I could not reproduce your problem.

- I ran your example with REddyProc version on CRAN on Ubuntu.
- I installed REddyProc newly from CRAN on a Windows machine with R version 3.4.3 and got finite values with your example.
- I implemented your example as a test case (based on the CRAN version) submitted a source-package to winbuilder. The tests were successfull (finite uStar) with the newest R version (R Under development (unstable) (2018-08-14 r75146).

The full output of resUStar on my machine is 
> resUStar[c("uStarTh", "seasonYear", "season", "tempInSeason")]
$uStarTh
```
  aggregationMode seasonYear  season     uStar
1          single         NA    <NA> 0.3670196
2            year       1998    <NA> 0.3670196
3          season       1998 1998001 0.3670196
4          season       1998 1998003 0.3670196
5          season       1998 1998006 0.3670196
6          season       1998 1998009 0.3670196
7          season       1998 1998012 0.3670196

$seasonYear
  seasonYear nRec uStarMaxSeason uStarAggr uStarPooled
1       1998 5551      0.3670196 0.3670196          NA

$season
  seasonYear  season nRec uStarSeasonEst uStarAggr
1       1998 1998001 1150             NA 0.3670196
2       1998 1998003 1218             NA 0.3670196
3       1998 1998006  779      0.3670196 0.3670196
4       1998 1998009 1644             NA 0.3670196
5       1998 1998012  760             NA 0.3670196

$tempInSeason
      1998001   1998003   1998006   1998009 1998012
 [1,]      NA        NA 0.2352243        NA      NA
 [2,]      NA        NA        NA        NA      NA
 [3,]      NA        NA        NA        NA      NA
 [4,]      NA        NA 0.3969457        NA      NA
 [5,]      NA        NA 0.5159020 0.3412740      NA
 [6,]      NA        NA        NA        NA      NA
 [7,]      NA 0.5776624        NA        NA      NA
 [8,]      NA        NA 0.2395189        NA      NA
 [9,]      NA        NA        NA        NA      NA
[10,]      NA        NA        NA        NA      NA
[11,]      NA        NA 0.3634230 0.3469542      NA
[12,]      NA        NA        NA        NA      NA
[13,]      NA 0.6377654        NA        NA      NA
[14,]      NA        NA 0.2878799        NA      NA
[15,]      NA        NA        NA        NA      NA
[16,]      NA        NA 0.3896183        NA      NA
[17,]      NA        NA 0.3706162        NA      NA
[18,]      NA 0.7258493        NA        NA      NA
```


Could you, please show the full output of resUStar?

Below some suggestions for locating the error:

Maybe this issue is related to your devtools problem. The uStar estimation uses some compiled C-code. Could you, please, check that your installation of RTools is properly set up so that REddyProc gets installed properly? 

Could you, please, check that the segmented function from the segmented package works properly on your system?

Could you, please, try constructing a working or failing example of the threshold estimation to data of a single season/temperature chunk (.e.g. season 1998006, temperature class 4) with function
`.estimateUStarSeasonCPTSeveralT` (in file [EddyUStarFilterChangePointDetection.R](https://github.com/bgctw/REddyProc/blob/c81827976d019d65c30bf9ca94270d088f48ce7c/R/EddyUStarFilterChangePointDetection.R))?
In my example it estimates uStarTh of 0.397 from the output above.

**Comment by lsigut** [comment] 2018-08-15 10:41
You are right, this could be connected with devtools that were not working properly. I was trying to solve it following these recommendations [https://github.com/r-lib/devtools/issues/1772](url) but it did not work. Then I realized the problem was trivial, as described here: [https://stackoverflow.com/questions/50034966/no-rtools-compatible-with-r-version-3-5-0-was-found](url). It did not automatically check the checkbox to modify system PATH. Now it seems that the `devtools::install_github("bgctw/REddyProc")` command works but I still get NAs. I will inspect further.

**Comment by lsigut** [comment] 2018-08-15 11:53
Hi,
thank you for pointing me towards the right direction! Most likely the problem was connected with package segmented! Now it works, though I did not realize it is also using random number generator. E.g. for `set.seed(816)` I get these results: 
```
aggregationMode   seasonYear  season     uStar 
1          single         NA    <NA> 0.3502545 
2            year       1998    <NA> 0.3502545 
3          season       1998 1998001 0.3502545 
4          season       1998 1998003 0.3502545 
5          season       1998 1998006 0.3502545 
6          season       1998 1998009 0.3502545 
7          season       1998 1998012 0.3502545
```
Now, what I actually originally intended to do was using `sEstUstarThresholdDistribution` method. I checked that it works fine now! Only there might be a small bug that it throws error when arg `probs` is assigned only one numeric value. I hope you can replicate the problem with this command:
```
(uStarRes <- EddyProc.C$sEstUstarThresholdDistribution(
  nSample = 5L, probs = 0.5,
  ctrlUstarEst.l = usControlUstarEst(isUsingCPTSeveralT = TRUE)))
```

Error:
```
Error in `[<-`(`*tmp*`, iInvalid, , value = NA_real_) : 
  (subscript) logical subscript too long
```

Actually it works if I repeat the probability value:
```
(uStarRes <- EddyProc.C$sEstUstarThresholdDistribution(
  nSample = 5L, probs = c(0.5, 0.5),
  ctrlUstarEst.l = usControlUstarEst(isUsingCPTSeveralT = TRUE)))
```
Thank you for your feedback! It was really helpful.

**Comment by bgctw** [comment] 2018-08-16 11:51
I opened a new issue #15 because last post describes a different problem.
Since, the fixing the segmented package resolved your problem, I close this issue.

**Closed by bgctw** 2018-08-16 11:51 UTC
